<a href="https://colab.research.google.com/github/RohitJaiswal01/World-Layoffs-SQL_Analysis/blob/main/ETL_DATA_Integration_World_layoffs_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
from io import StringIO

# URL of the raw CSV file from GitHub
url = 'https://raw.githubusercontent.com/RohitJaiswal01/World-Layoffs-SQL_Analysis/refs/heads/main/layoffs_2023_uncleaned.csv'

# Send GET request to fetch the raw CSV file
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Convert the content of the CSV into a pandas DataFrame
    csv_data = StringIO(response.text)
    df = pd.read_csv(csv_data)
    print(df.head())  # Display first few rows of the DataFrame
else:
    print(f"Failed to fetch CSV. Status code: {response.status_code}")

     company       location     industry  total_laid_off  percentage_laid_off  \
0  Atlassian         Sydney        Other           500.0                 0.05
1   SiriusXM  New York City        Media           475.0                 0.08
2     Alerzo         Ibadan       Retail           400.0                  NaN
3     UpGrad         Mumbai    Education           120.0                  NaN
4       Loft      Sao Paulo  Real Estate           340.0                 0.15

       date     stage        country  funds_raised_millions
0  3/6/2023  Post-IPO      Australia                  210.0
1  3/6/2023  Post-IPO  United States                  525.0
2  3/6/2023  Series B        Nigeria                   16.0
3  3/6/2023   Unknown          India                  631.0
4  3/3/2023   Unknown         Brazil                  788.0

In [2]:
# Saving dataset in a csv format te be processed in MySQL
df.to_csv("layoffs")
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0